-- MySQL Script generated by MySQL Workbench
-- Sat Oct  2 18:30:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bases2N_G12` DEFAULT CHARACTER SET utf8 ;
USE `Bases2N_G12` ;

-- -----------------------------------------------------
-- Table `Bases2N_G12`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bases2N_G12`.`Banco` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bases2N_G12`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bases2N_G12`.`Periodo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bases2N_G12`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bases2N_G12`.`Reporte` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Activo` BIGINT NULL,
  `Pasivo` BIGINT NULL,
  `Capital` BIGINT NULL,
  `Banco_Id` INT ,
  `Fecha_Id` INT ,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
